version: "3.7"

services:
  backend:
    build: ./back/
    container_name: backend
    ports:
      - "4003:4003"
    depends_on:
      - bookmarker-database
  bookmarker-database:
    image: mongo:4.2
    container_name: bookmarker-database
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-bookmarker}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-#10D}
    volumes:
      - ./database/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"