version: "3.7"

services:
  bookmarker-backend:
    build: ./back/
    container_name: bookmarker-backend
    ports:
      - "4003:4003"
    depends_on:
      - bookmarker-database
    links:
      - bookmarker-database
    environment: 
      MONGODB_DB_URI: ${MONGODB_DB_URI:-bookmarker-database}
  bookmarker-database:
    image: mongo:4.2
    container_name: bookmarker-database
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-bookmarker}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-#10D}
    volumes:
      - ./database/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
  frontend:
    build: ./front/
    container_name: frontend
    ports:
      - "80:80"